language: node_js
node_js:
- '12'
cache:
  yarn: true
script:
- yarn lint
- yarn test
- node-sass styles/*
before_install:
- npm install -g yarn
- yarn install
notifications:
  email: false
  slack:
    secure: PCKXd+WtnwbTlRIYuVShYK/mmRnkJc9qKTMr8XD+6SxmdOjoWcG117NdQPb60NjpWObZxQR6mQpE55mmr00ofruMvrj77DFy1dnyGlulflHW3yJ4h6YpARYGOJ9sYIY1SkfBRrA2FInpZiXG0EQRFRCKy9O/nrw1cDYbRRc0XW7XWJmVLuTmlMIK9nsRDonyV7T38gH4X1vtwlEq0PsMmt10nbbD/4wroHR3Qz3b/Ly+pyEJ1i5iAQECVYStPL93koXky6OwsJddv1l/6brGX5yFQEaTWwESKfqJbnBTFnHe8JNCrphB5TZmRSyfb0Vpq8G39dy9AP/MsIBuIWy15m6QNSjdFOWQlfevE9dFirrfczx8fEgj4bS8PauFLSyzVb+vr1Ud6E4SXr4rBkIdEd9mQdH6T+LkM5vmnYv9LNFrEOoEE8pNeOshdvdAHHOWLZkMwXyFbKfzunY+4+7Tgwqetw5xBcwTcl8kW6x20CJqUPS6piz0vTaHgtxCxWhPmtSiu4q8oglpS0uYbk8sWeST/8BIrdty2gRB1apqjGRxUzrEmkrF910mErjuZDeCDdo/8nFTTIoGI/hkTEuKRUo+mOTg4YzhYUgIXucSJ0Vw4ob0OPsFZiCZeUYhnVwgZh7zZIRwlaM3amwdB2ghWaR2Ew5kkcMR1bwAoeOUvws=
